name: Kitchensink R3F
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install node dependencies
        uses: bahmutov/npm-install@v1

      - name: build package
        run: yarn workspace @appactions/core build

      - name: build browser extension
        run: yarn workspace browser-extension build

      - name: test browser extension
        run: yarn workspace browser-extension test
