name: ci
on: [deployment_status]
jobs:
  Debug:
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  Cypress:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.sha }}',
              state: 'pending',
              context: 'Cypress',
              description: 'Waiting...',
            })

      - name: Checkout 🛎
        uses: actions/checkout@v1

      - name: Run Cypress 🌲
        uses: cypress-io/github-action@v2
        # let's give this action an ID so we can refer to its output values later
        id: cypress
        # continue the build in case of an error, as we need to set the commit status in the next step
        continue-on-error: true
        with:
          working-directory: ./restaurant-reviewer
          record: true
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Cypress tests ✅
        uses: actions/github-script@v3
        if: ${{ success() }}
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.sha }}',
              state: 'success',
              context: 'Cypress',
              description: 'Cypress tests passed',
              target_url: '${{ steps.cypress.outputs.dashboardUrl }}'
            })

      - name: Cypress tests 🚨
        uses: actions/github-script@v3
        if: ${{ failure() }}
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.sha }}',
              state: 'failure',
              context: 'Cypress',
              description: 'Cypress tests failed',
              target_url: '${{ steps.cypress.outputs.dashboardUrl }}'
            })

  Puppeteer:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.sha }}',
              state: 'pending',
              context: 'Puppeteer',
              description: 'Waiting...',
            })

      - name: Checkout 🛎
        uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: yarn install

      - name: Run Puppeteer 🍍
        id: puppeteer
        working-directory: ./restaurant-reviewer
        continue-on-error: true
        env:
          PUPPETEER_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CI: true
        run: node puppeteer/test.js

      - name: Puppeteer tests ✅
        uses: actions/github-script@v3
        if: ${{ success() }}
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.sha }}',
              state: 'success',
              context: 'Puppeteer',
              description: 'Puppeteer tests passed',
              target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })

      - name: Puppeteer tests 🚨
        uses: actions/github-script@v3
        if: ${{ failure() }}
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.sha }}',
              state: 'failure',
              context: 'Puppeteer',
              description: 'Puppeteer tests failed',
              target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })

  react-app-actions-backend:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.sha }}',
              state: 'pending',
              context: 'react-app-actions-backend',
              description: 'Waiting...',
            })

      - name: Checkout 🛎
        uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - run: yarn install

      - name: Build and Test react-app-actions-backend 🍍
        working-directory: ./react-app-actions-backend
        continue-on-error: true
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}
          CI: true
        run: yarn build-and-test

      - name: react-app-actions-backend tests ✅
        uses: actions/github-script@v3
        if: ${{ success() }}
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.sha }}',
              state: 'success',
              context: 'react-app-actions-backend',
              description: 'backend tests passed',
              target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })

      - name: react-app-actions-backend tests 🚨
        uses: actions/github-script@v3
        if: ${{ failure() }}
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.sha }}',
              state: 'failure',
              context: 'react-app-actions-backend',
              description: 'backend tests failed',
              target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })
