name: Cypress
on: [deployment_status]
jobs:
  main:
    if: github.event.deployment_status.environment == 'kitchensink' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    concurrency: deploy-${{ github.head_ref }}
    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install node dependencies
        uses: bahmutov/npm-install@v1

      - name: run cypress
        id: cypress
        run: yarn workspace kitchensink-nextjs cypress
        env:
          CI: true
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # - name: run cypress
      #   uses: cypress-io/github-action@v2
      #   id: cypress
      #   with:
      #     working-directory: ./kitchensink-nextjs
      #     record: true
      #   env:
      #     CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # - name: add a check to display the cypress dashboard
      #   uses: octokit/request-action@v2.x
      #   if: always()
      #   with:
      #     route: POST /repos/:repository/statuses/:sha
      #     repository: ${{ github.repository }}
      #     sha: ${{ github.sha }}
      #     state: ${{ job.status }}
      #     target_url: ${{ steps.cypress.outputs.dashboardUrl }}
      #     context: Cypress Dashboard
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GREN_CI_CD_GITHUB_TOKEN }}
