name: ci
on: [deployment_status]
jobs:
  tests:
    if: github.event.deployment_status.environment == 'Preview – restaurant-reviewer' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.sha }}',
              state: 'pending',
              context: 'Cypress',
              description: 'Waiting...',
            })

      - name: Checkout 🛎
        uses: actions/checkout@v1

      - name: Run Cypress 🌲
        uses: cypress-io/github-action@v2
        # let's give this action an ID so we can refer to its output values later
        id: cypress
        # continue the build in case of an error, as we need to set the commit status in the next step
        continue-on-error: true
        with:
          working-directory: ./restaurant-reviewer
          record: true
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Cypress tests ✅
        uses: actions/github-script@v3
        if: ${{ success() }}
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.sha }}',
              state: 'success',
              context: 'Cypress',
              description: 'Cypress tests passed',
              target_url: '${{ steps.cypress.outputs.dashboardUrl }}'
            })

      - name: Cypress tests 🚨
        uses: actions/github-script@v3
        if: ${{ failure() }}
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.sha }}',
              state: 'failure',
              context: 'Cypress',
              description: 'Cypress tests failed',
              target_url: '${{ steps.cypress.outputs.dashboardUrl }}'
            })
