name: Unit tests
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install node dependencies
        uses: bahmutov/npm-install@v1

      - name: build package
        run: yarn workspace @appactions/cypress build

      - name: run unit tests
        id: cypress
        run: yarn workspace @appactions/cypress test
        env:
          CI: true
          CYPRESS_RECORD_KEY_FOR_APP_ACTIONS: ${{ secrets.CYPRESS_RECORD_KEY_FOR_APP_ACTIONS}}
