name: Unit tests
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install packages
        run: yarn install

      - name: build package
        run: yarn workspace @appactions/core build

      - name: run unit tests
        run: yarn workspace @appactions/core test:cypress
        env:
          CI: true
          CYPRESS_RECORD_KEY_FOR_APP_ACTIONS: ${{ secrets.CYPRESS_RECORD_KEY_FOR_APP_ACTIONS}}

      - name: run jest tests
        run: yarn workspace @appactions/core test:jest
        env:
          CI: true
